# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
before_install:
- gem install cocoapods --pre # At this time of writing, 1.0.1 does not support Xcode 8
script:
- set -o pipefail && xcodebuild test -workspace Example/RangeTree.xcworkspace -scheme RangeTree-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty
- pod lib lint
